language: node_js
node_js:
  - '16'

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  email:
    on_failure: always

branches:
  only:
    - main
